version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gophers-microservice
    ports:
      - "5436:5432"

  product-service:
    build:
      context: product-service
      dockerfile: deployments/deploy/product-service.dockerfile
    container_name: product-service
    depends_on:
      - postgres
    ports:
      - "8080:8080"